### ISSUE TITLE
Add login/register UI

### ISSUE THREAD

**Issue by dsibinski** [aliyorulmazdev/NC#17]
As you have already implemented the server-side authentication, it's now time to add login/register pages to your frontend.

I should be able to register in the application and login. There should be a possibility to remember my login, so I don't need to re-login after closing and opening my web browser again.

Please consider that the data in your application will be stored per-user. It means that everything that a person will create inside of your app will be his/her own data. Other users will not see the products created by me.
You don't need to implement this within this task (I will create a separate task for that), but already have that in mind.

**Comment by aliyorulmazdev** [comment]
i will try to implement this. will store token on user browser. This way after user logins. If he/she doesnt clear browser cache my login page should automaticly checks it and login without need any addional information.

**Comment by aliyorulmazdev** [comment]
done via #15 merge
