### ISSUE TITLE
Change categories to be defined per-user

### ISSUE THREAD

**Issue by dsibinski** [aliyorulmazdev/NC#20]
This should be done after #18 

**The problem**
Currently, both the categories are global in the whole application. They are hard-coded in `export const categoryOptions`.
This request is to change that to be defined per-user with some defaults for each user.

**Desired solution**
When I register as a new user in the app, I want to have 4 default categories to be available to me: 
* Clothes
* Shoes
* Accessories
* Watches

I can freely remove all those categories, which will not affect other users' categories.

Also, when I add a new category, it will only be visible to me and not to other users.

These requirements mean that first you need to make it possible to create categories in the app, not be hard-coded.

**Comment by BeratARPA** [comment]
I'm pleased to inform you that I have successfully completed this issue, addressing all the necessary tasks and requirements.
