### ISSUE TITLE
Make Product's edit form be displayed on a separate page

### ISSUE THREAD

**Issue by dsibinski** [aliyorulmazdev/NC#6]
Currently, the product's details form is displayed alongside the list of products:

![image](https://github.com/aliyorulmazdev/NC/assets/7132073/790e7b51-cfda-43e1-a3d4-3ec02395d7b1)

Please change it to be displayed separately, on its own page. It should work like that for both adding a new item and editing an existing one. The same form should be reused in both cases.

**Comment by aliyorulmazdev** [comment]
Solved on #10
